use std::fs;

use graf::{
    index,
    model::{Coverage, Direction, FileFacts, GraphSnapshot, Node, QueryOptions, Reference},
    parser::{PythonContext, parse_python, parse_python_with_source_root},
    query::SearchOptions,
    store::Store,
};
use tempfile::tempdir;

fn parse(source: &str) -> FileFacts {
    let facts = parse_python("src/pkg/sample.py", source, "fixture").unwrap();
    assert!(facts.diagnostics.is_empty(), "{:?}", facts.diagnostics);
    facts
}

fn node<'a>(facts: &'a FileFacts, name: &str) -> &'a Node {
    facts
        .nodes
        .iter()
        .find(|n| n.qualified_name.as_deref() == Some(name))
        .unwrap()
}

fn reference<'a>(facts: &'a FileFacts, owner: &str, label: &str, relation: &str) -> &'a Reference {
    let id = &node(facts, owner).id;
    facts
        .references
        .iter()
        .find(|r| r.source == *id && r.label == label && r.relation == relation)
        .unwrap()
}

fn context(facts: &FileFacts, owner: &str, label: &str, expected: &str) {
    let reference = reference(facts, owner, label, "references");
    assert!(
        node(facts, owner).metadata["python_references"]
            .as_array()
            .unwrap()
            .iter()
            .any(|e| { e["reference_id"] == reference.id && e["context"] == expected })
    );
}

#[test]
fn rationale_uses_ast_locations_and_actual_nested_owners() {
    let facts = parse(
        r##"#!/usr/bin/env python3
# coding: utf-8
"""Keep a local journal because network access is optional."""
class Journal:
    # introductory comment
    """Entries survive retries because append operations are idempotent."""
    @property
    def size(self):
        """Return a stable count because callers compare successive reads."""
        # WHY: exclude pending writes until they are committed
        def pending():
            """Keep pending writes separate because their transaction can fail."""
            pass
        return 0
fake = """
# NOTE: this is string content, not a comment
"""
# FIXME: remove the compatibility path after migration
"##,
    );
    let rationale: Vec<_> = facts
        .nodes
        .iter()
        .filter(|n| n.kind == "rationale")
        .collect();
    assert_eq!(rationale.len(), 6);
    assert!(!rationale.iter().any(|n| n.label.contains("string content")));
    let module_doc = rationale
        .iter()
        .find(|n| n.label.contains("local journal"))
        .unwrap();
    assert_eq!(module_doc.line, Some(3));
    for (text, owner) in [
        ("Entries survive", "Journal"),
        ("stable count", "Journal.size"),
        ("WHY:", "Journal.size"),
        ("pending writes separate", "Journal.size.pending"),
    ] {
        let rationale = rationale.iter().find(|n| n.label.contains(text)).unwrap();
        assert!(facts.edges.iter().any(|e| e.source == rationale.id
            && e.target == node(&facts, owner).id
            && e.relation == "rationale_for"));
    }
    assert!(
        rationale
            .iter()
            .all(|n| n.metadata["source_text"].is_string())
    );
}

#[test]
fn only_docstrings_and_selected_comments_become_rationale() {
    for source in [
        "x = 1\n'''This is a later expression and never a module docstring.'''\n",
        "b'''Bytes are not documentation even if this text is long.'''\n",
        "f'''Interpolation is not documentation even if this text is long.'''\n",
        "'''Tiny.'''\n# ordinary prose comment\n",
    ] {
        assert!(
            !parse(source).nodes.iter().any(|n| n.kind == "rationale"),
            "{source}"
        );
    }
    let facts = parse("('This rationale is split ' 'across adjacent literals for readability.')\n");
    assert_eq!(
        facts.nodes.iter().filter(|n| n.kind == "rationale").count(),
        1
    );
    for prefix in [
        "NOTE",
        "IMPORTANT",
        "HACK",
        "WHY",
        "RATIONALE",
        "TODO",
        "FIXME",
    ] {
        let facts = parse(&format!("# {prefix}: preserve the source evidence\n"));
        assert_eq!(
            facts.nodes.iter().filter(|n| n.kind == "rationale").count(),
            1
        );
    }
}

#[test]
fn generated_module_docs_are_suppressed_without_losing_function_docs() {
    for marker in [
        "revision: str = 'v2'\ndown_revision = 'v1'\ndef upgrade(): pass\n",
        "from django.db import migrations\nclass Migration(migrations.Migration):\n    operations = []\n",
        "# Generated by the protocol buffer compiler. DO NOT EDIT!\n",
        "# @generated by a schema tool\n",
    ] {
        let facts = parse(&format!(
            "'''This module annotation is generated boilerplate.'''\n{marker}\ndef custom():\n    '''Preserve the original ordering because downstream consumers rely on it.'''\n    pass\n"
        ));
        let rationale: Vec<_> = facts
            .nodes
            .iter()
            .filter(|n| n.kind == "rationale")
            .collect();
        assert_eq!(rationale.len(), 1, "{marker}");
        assert!(rationale[0].label.contains("original ordering"));
    }
    let ordinary =
        parse("'''Track revision history because edits must be reversible.'''\nrevision = 42\n");
    assert!(ordinary.nodes.iter().any(|n| n.kind == "rationale"));
}

#[test]
fn decorators_have_definition_owners_and_keep_uncertain_exports() {
    let facts = parse(
        "def traced(fn): return fn\nfrom policies import retry\nimport routes as r\n@traced\n@retry(attempts=2)\ndef work(): pass\nclass API:\n    @r.route('/')\n    def index(self): pass\n@traced\nclass Service: pass\n",
    );
    for (owner, label, key) in [
        ("work", "traced", "python:pkg.sample:traced"),
        ("work", "retry", "python:policies:retry"),
        ("API.index", "r.route", "python:routes:route"),
        ("Service", "traced", "python:pkg.sample:traced"),
    ] {
        context(&facts, owner, label, "decorator");
        assert_eq!(
            reference(&facts, owner, label, "references").candidate_keys,
            [key]
        );
        assert!(node(&facts, owner).binding_key.is_none());
    }
    assert_eq!(
        facts
            .references
            .iter()
            .filter(|r| r.relation == "calls" && r.label == "retry")
            .count(),
        1
    );
}

#[test]
fn builtin_decorator_noise_is_suppressed_but_shadowed_names_are_retained() {
    let facts = parse(
        "from dataclasses import dataclass\nimport functools\n@dataclass\nclass Model:\n    @property\n    def value(self): return 1\n    @staticmethod\n    def make(): pass\n@functools.wraps(Model)\ndef wrapper(): pass\n",
    );
    assert!(
        !facts
            .references
            .iter()
            .any(|r| r.id.starts_with("references:decorator:"))
    );
    let shadowed = parse(
        "def property(fn): return fn\nclass Model:\n    @property\n    def value(self): return 1\n",
    );
    assert_eq!(
        reference(&shadowed, "Model.value", "property", "references").candidate_keys,
        ["python:pkg.sample:property"]
    );
}

#[test]
fn annotations_emit_contextual_references_and_never_annotation_calls() {
    for prelude in ["", "from __future__ import annotations\n"] {
        let facts = parse(&format!(
            "{prelude}from .model import Payload, Result, Base\nfrom typing import Literal, Annotated\ndef factory(): pass\nclass Service(Base):\n    field: Payload\n    def process(self, item: list[Payload], extra: 'Payload' = factory()) -> Result:\n        local: Payload\n        return Result()\ndef opaque(x: factory(), y: Literal['Payload'], z: Annotated[Payload, 'Result']) -> factory(): pass\n"
        ));
        context(&facts, "Service.process", "Payload", "generic_arg");
        context(&facts, "Service.process", "Result", "return_type");
        context(&facts, "Service", "Payload", "variable_type");
        assert_eq!(
            reference(&facts, "Service", "Base", "inherits").candidate_keys,
            ["python:pkg.model:Base"]
        );
        assert!(
            facts
                .references
                .iter()
                .any(|r| r.id.starts_with("references:parameter_type:") && r.label == "Payload")
        );
        assert_eq!(
            facts
                .references
                .iter()
                .filter(|r| r.relation == "calls" && r.label == "factory")
                .count(),
            1
        );
        assert!(
            !facts
                .references
                .iter()
                .any(|r| r.source == node(&facts, "opaque").id && r.label == "Result")
        );
    }
}

#[test]
fn type_and_base_references_do_not_fall_through_shadowed_bindings() {
    let facts = parse(
        "from model import Payload, Base\ndef outer(Payload):\n    def inner(value: Payload): pass\nBase = replacement\nclass Service(Base): pass\n",
    );
    assert!(
        reference(&facts, "outer.inner", "Payload", "references")
            .candidate_keys
            .is_empty()
    );
    assert!(
        reference(&facts, "Service", "Base", "inherits")
            .candidate_keys
            .is_empty()
    );
}

#[test]
fn explicit_source_roots_preserve_file_identity_and_relative_packages() {
    let facts = parse_python_with_source_root(
        "lib/python/pkg/api/__init__.py",
        "from ..model import Payload\ndef run(): return Payload()\n",
        "fixture",
        Some("lib/python"),
    )
    .unwrap();
    assert_eq!(facts.module, "pkg.api");
    assert_eq!(facts.path, "lib/python/pkg/api/__init__.py");
    assert_eq!(
        reference(&facts, "run", "Payload", "calls").candidate_keys,
        ["python:pkg.model:Payload"]
    );
    let literal_src =
        parse_python_with_source_root("src/file.py", "", "fixture", Some("")).unwrap();
    assert_eq!(literal_src.module, "src.file");
    for root in [
        "/lib",
        "../lib",
        "lib/",
        "lib//python",
        "lib\\python",
        "other",
    ] {
        assert!(
            parse_python_with_source_root("lib/python/pkg/api.py", "", "fixture", Some(root))
                .is_err(),
            "{root}"
        );
    }
    let too_deep = parse_python_with_source_root(
        "lib/python/pkg/api.py",
        "from ...model import Payload\n",
        "fixture",
        Some("lib/python"),
    )
    .unwrap();
    assert!(too_deep.references[0].candidate_keys.is_empty());
}

#[test]
fn class_member_aliases_require_a_verified_class_and_unshadowed_method() {
    let good = parse(
        "class lower_case:\n    @staticmethod\n    def work(): pass\n    @classmethod\n    def make(cls): pass\ndef run():\n    lower_case.work()\n    lower_case.make()\n",
    );
    assert_eq!(
        reference(&good, "run", "lower_case.work", "calls").candidate_keys,
        ["python-member:pkg.sample:lower_case.work"]
    );
    assert_eq!(
        node(&good, "lower_case.work").metadata["binding_aliases"][0],
        "python-member:pkg.sample:lower_case.work"
    );
    for source in [
        "def Factory():\n    def work(): pass\n",
        "class Factory:\n    @custom\n    def work(): pass\n",
        "class Factory:\n    def work(): pass\n    work = replacement\n",
        "class Factory:\n    @staticmethod\n    def work(): pass\nFactory = replacement\n",
        "staticmethod = custom\nclass Factory:\n    @staticmethod\n    def work(): pass\n",
        "@custom\nclass Factory:\n    class Nested:\n        def work(): pass\n",
    ] {
        let facts = parse(source);
        assert!(
            facts
                .nodes
                .iter()
                .all(|n| n.metadata["binding_aliases"]
                    .as_array()
                    .is_none_or(|aliases| aliases.iter().all(|alias| !alias
                        .as_str()
                        .unwrap()
                        .starts_with("python-member:pkg.sample:")))),
            "{source}"
        );
    }
    let dynamic = parse(
        "class Service:\n    def work(self): pass\ndef run(Service, receiver):\n    Service.work()\n    receiver.work()\n",
    );
    assert!(
        dynamic
            .references
            .iter()
            .filter(|r| r.relation == "calls")
            .all(|r| r.candidate_keys.is_empty())
    );
}

#[test]
fn imported_class_and_relative_module_members_resolve_without_function_guessing() {
    let dir = tempdir().unwrap();
    let mut store = Store::create(&dir.path().join("index.db")).unwrap();
    let provider = parse_python("src/pkg/model.py", "class Service:\n    @staticmethod\n    def work(): pass\ndef Factory():\n    def work(): pass\ndef helper(): pass\n", "provider").unwrap();
    let consumer = parse_python("src/pkg/api.py", "from .model import Service, Factory\nfrom . import model\ndef run():\n    Service.work()\n    Factory.work()\n    model.helper()\n", "consumer").unwrap();
    let service = node(&provider, "Service.work").id.clone();
    let nested = node(&provider, "Factory.work").id.clone();
    let helper = node(&provider, "helper").id.clone();
    store
        .apply_native(
            "fixture-root",
            vec![provider, consumer],
            vec![],
            Coverage::default(),
        )
        .unwrap();
    let graph = store.snapshot().unwrap();
    let calls: Vec<_> = graph
        .edges
        .iter()
        .filter(|e| e.relation == "calls")
        .collect();
    assert_eq!(calls.len(), 2);
    assert!(calls.iter().any(|e| e.target == service));
    assert!(calls.iter().any(|e| e.target == helper));
    assert!(!calls.iter().any(|e| e.target == nested));
    // Replacing the class with a function removes the old member alias and edge.
    let changed = parse_python(
        "src/pkg/model.py",
        "def Service():\n    def work(): pass\ndef helper(): pass\n",
        "changed",
    )
    .unwrap();
    store
        .apply_native("fixture-root", vec![changed], vec![], Coverage::default())
        .unwrap();
    assert!(
        !store
            .snapshot()
            .unwrap()
            .edges
            .iter()
            .any(|e| e.relation == "calls" && e.target == service)
    );
}

#[test]
fn rationale_labels_preserve_words_unicode_and_long_first_tokens() {
    for text in [
        "This service reconciles queued deliveries in order because duplicate acknowledgements can arrive after reconnecting.",
        "é".repeat(100).as_str(),
        "https://example.invalid/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    ] {
        let facts = parse(&format!("\"\"\"{text}\"\"\"\n"));
        let rationale = facts.nodes.iter().find(|n| n.kind == "rationale").unwrap();
        assert!(rationale.label.chars().count() <= 80);
        assert!(rationale.label.ends_with('…'));
        assert!(rationale.label.chars().count() > 1);
        assert_eq!(rationale.metadata["text"], text);
        if text.contains(' ') {
            let prefix = rationale.label.trim_end_matches('…');
            assert!(text[prefix.len()..].starts_with(' '));
        }
    }
}

fn inventory(files: &[(&str, &str)]) -> Vec<FileFacts> {
    files
        .iter()
        .map(|(path, source)| {
            let facts =
                parse_python(path, source, &blake3::hash(source.as_bytes()).to_hex()).unwrap();
            assert!(
                facts.diagnostics.is_empty(),
                "{path}: {:?}",
                facts.diagnostics
            );
            facts
        })
        .collect()
}

fn contextualize(mut facts: Vec<FileFacts>) -> Vec<FileFacts> {
    let context = PythonContext::from_facts(&facts);
    for file in &mut facts {
        context.apply(file);
    }
    facts
}

fn pairs(graph: &GraphSnapshot, relation: &str) -> Vec<(String, String)> {
    graph
        .edges
        .iter()
        .filter(|e| e.relation == relation)
        .map(|e| {
            let source = graph.nodes.iter().find(|n| n.id == e.source).unwrap();
            let target = graph.nodes.iter().find(|n| n.id == e.target).unwrap();
            (
                source.label.clone(),
                format!(
                    "{}:{}",
                    target.file,
                    target.qualified_name.as_deref().unwrap_or(&target.label)
                ),
            )
        })
        .collect()
}

#[test]
fn package_and_public_alias_chains_resolve_to_original_symbols_and_members() {
    let files = inventory(&[
        (
            "src/pkg/impl.py",
            "def execute(): pass\nclass Engine:\n    @staticmethod\n    def build(): pass\n",
        ),
        (
            "src/pkg/api.py",
            "from .impl import execute as Public, Engine as PublicType\n",
        ),
        (
            "src/pkg/__init__.py",
            "from .api import Public as entry, PublicType as Shape\nimport pkg.impl as backend\n",
        ),
        (
            "app.py",
            "from pkg import entry, Shape, backend\nimport pkg as package\ndef run():\n    entry()\n    package.entry()\n    Shape.build()\n    backend.execute()\n",
        ),
    ]);
    let native_ids: Vec<_> = files
        .iter()
        .flat_map(|f| f.nodes.iter().map(|n| n.id.clone()))
        .collect();
    let files = contextualize(files);
    assert_eq!(
        native_ids,
        files
            .iter()
            .flat_map(|f| f.nodes.iter().map(|n| n.id.clone()))
            .collect::<Vec<_>>()
    );
    let dir = tempdir().unwrap();
    let mut store = Store::create(&dir.path().join("index.db")).unwrap();
    store
        .apply_native("fixture-root", files, vec![], Coverage::default())
        .unwrap();
    let graph = store.snapshot().unwrap();
    let calls = pairs(&graph, "calls");
    assert_eq!(calls.len(), 4, "{calls:?}");
    assert_eq!(
        calls
            .iter()
            .filter(|(_, target)| target == "src/pkg/impl.py:execute")
            .count(),
        3
    );
    assert!(calls.contains(&("run".into(), "src/pkg/impl.py:Engine.build".into())));
    assert!(pairs(&graph, "imports").contains(&("app".into(), "src/pkg/impl.py:execute".into())));
    assert!(
        pairs(&graph, "re_exports")
            .contains(&("pkg.api".into(), "src/pkg/impl.py:pkg.impl".into()))
    );
}

#[test]
fn forwarding_does_not_infer_dynamic_or_shadowed_exports() {
    for package in [
        "from .impl import execute as entry\nentry = factory()\n",
        "from .impl import execute as entry\ndel entry\n",
        "if enabled:\n    from .impl import execute as entry\n",
        "from .impl import execute as entry\nfrom .other import execute as entry\n",
        "from .impl import *\n__all__ = ['entry']\n",
        "from .impl import execute as _hidden\n__all__ = compute_exports()\n",
        "from .impl import execute as entry\nglobals()['entry'] = replacement\n",
        "from .impl import execute as entry\nentry.attribute = replacement\n",
    ] {
        let files = contextualize(inventory(&[
            ("pkg/impl.py", "def execute(): pass\n"),
            ("pkg/other.py", "def execute(): pass\n"),
            ("pkg/__init__.py", package),
            (
                "consumer.py",
                "from pkg import entry, _hidden\ndef run():\n    entry()\n    _hidden()\n",
            ),
        ]));
        let dir = tempdir().unwrap();
        let mut store = Store::create(&dir.path().join("index.db")).unwrap();
        store
            .apply_native("fixture-root", files, vec![], Coverage::default())
            .unwrap();
        assert!(
            !pairs(&store.snapshot().unwrap(), "calls")
                .iter()
                .any(|(source, _)| source == "run"),
            "{package}"
        );
    }
    // __all__ mutations cannot erase an explicit named import, or invent a star export.
    let files = contextualize(inventory(&[
        ("pkg/impl.py", "def execute(): pass\n"),
        (
            "pkg/__init__.py",
            "from .impl import execute as entry\n__all__ = []\n__all__.extend(compute_exports())\n",
        ),
        ("consumer.py", "from pkg import entry\ndef run(): entry()\n"),
        ("star.py", "from pkg import *\ndef run_star(): entry()\n"),
    ]));
    assert_eq!(
        reference(&files[2], "run", "entry", "calls").candidate_keys,
        ["python:pkg.impl:execute"]
    );
    assert!(
        reference(&files[3], "run_star", "entry", "calls")
            .candidate_keys
            .is_empty()
    );
}

#[test]
fn missing_or_cyclic_export_does_not_fall_back_to_a_same_named_submodule() {
    for package in [
        "from .missing import absent as entry\n",
        "from .api import entry\n",
    ] {
        let files = contextualize(inventory(&[
            ("pkg/__init__.py", package),
            ("pkg/api.py", "from . import entry\n"),
            ("pkg/entry.py", "def execute(): pass\n"),
            ("consumer.py", "from pkg import entry\ndef run(): entry()\n"),
        ]));
        let consumer = &files[3];
        assert!(
            !consumer
                .references
                .iter()
                .filter(|r| r.relation == "imports")
                .flat_map(|r| &r.candidate_keys)
                .any(|key| key == "module:pkg.entry")
        );
        assert!(
            !reference(consumer, "run", "entry", "calls")
                .candidate_keys
                .iter()
                .any(|key| key == "python:pkg.entry:execute")
        );
        if package.contains(".api") {
            assert!(
                reference(consumer, "run", "entry", "calls")
                    .candidate_keys
                    .is_empty()
            );
        }
    }
}

#[test]
fn forwarding_fingerprint_ignores_body_hashes_locations_and_ordinary_definitions() {
    let first = inventory(&[
        ("pkg/impl.py", "def execute(): return 1\n"),
        ("pkg/__init__.py", "from .impl import execute as entry\n"),
    ]);
    let mut second = inventory(&[
        (
            "pkg/impl.py",
            "def execute():\n    value = 2\n    return value\ndef unrelated(): pass\n",
        ),
        (
            "pkg/__init__.py",
            "# changed leading prose\n\nfrom .impl import execute as entry\n",
        ),
    ]);
    second.reverse();
    // Defining-key deletion/restoration is handled by Store, without reparsing
    // callers whose explicit origin key has not changed.
    assert_eq!(
        PythonContext::from_facts(&first).fingerprint(),
        PythonContext::from_facts(&first[1..]).fingerprint()
    );
    assert_eq!(
        PythonContext::from_facts(&first).fingerprint(),
        PythonContext::from_facts(&second).fingerprint()
    );
    second[0] = parse_python(
        "pkg/__init__.py",
        "from .impl import unrelated as entry\n",
        "another",
    )
    .unwrap();
    assert_ne!(
        PythonContext::from_facts(&first).fingerprint(),
        PythonContext::from_facts(&second).fingerprint()
    );
}

#[test]
fn index_updates_forwarded_targets_removal_and_body_only_edits() {
    let dir = tempdir().unwrap();
    fs::create_dir(dir.path().join("pkg")).unwrap();
    fs::write(
        dir.path().join("pkg/impl.py"),
        "def first(): return 1\ndef second(): return 2\n",
    )
    .unwrap();
    let barrel = dir.path().join("pkg/__init__.py");
    fs::write(&barrel, "from .impl import first as entry\n").unwrap();
    fs::write(
        dir.path().join("app.py"),
        "from pkg import entry\ndef run(): return entry()\n",
    )
    .unwrap();
    let db = dir.path().join(".graf/index.db");
    index::run(dir.path(), &db).unwrap();
    let snapshot = || Store::open(&db).unwrap().snapshot().unwrap();
    assert_eq!(
        pairs(&snapshot(), "calls"),
        [("run".into(), "pkg/impl.py:first".into())]
    );
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    fs::write(
        dir.path().join("pkg/impl.py"),
        "def first(): return 9\ndef second(): return 2\n",
    )
    .unwrap();
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 1);
    assert_eq!(
        pairs(&snapshot(), "calls"),
        [("run".into(), "pkg/impl.py:first".into())]
    );
    fs::write(&barrel, "from .impl import second as entry\n").unwrap();
    index::run(dir.path(), &db).unwrap();
    assert_eq!(
        pairs(&snapshot(), "calls"),
        [("run".into(), "pkg/impl.py:second".into())]
    );
    fs::write(&barrel, "# public alias removed\n").unwrap();
    index::run(dir.path(), &db).unwrap();
    assert!(pairs(&snapshot(), "calls").is_empty());
    fs::write(&barrel, "from .impl import second as entry\n").unwrap();
    index::run(dir.path(), &db).unwrap();
    assert_eq!(pairs(&snapshot(), "calls").len(), 1);
    fs::remove_file(dir.path().join("pkg/impl.py")).unwrap();
    index::run(dir.path(), &db).unwrap();
    assert!(pairs(&snapshot(), "calls").is_empty());
}

#[test]
fn incremental_submodule_fallback_eligibility_matches_fresh_index() {
    let dir = tempdir().unwrap();
    let db = dir.path().join(".graf/index.db");
    let fresh_db = dir.path().join(".graf/fresh.db");
    fs::create_dir(dir.path().join("pkg")).unwrap();
    let package = dir.path().join("pkg/__init__.py");
    let child = dir.path().join("pkg/child.py");
    fs::write(dir.path().join("helper.py"), "def marker(): pass\n").unwrap();
    fs::write(&package, "from helper import marker\n").unwrap();
    fs::write(dir.path().join("consumer.py"), "from pkg import child\n").unwrap();
    fs::write(dir.path().join("unrelated.py"), "def keep(): return 1\n").unwrap();
    index::run(dir.path(), &db).unwrap();
    let unrelated = || {
        let graph = Store::open_read_only(&db).unwrap().snapshot().unwrap();
        serde_json::to_value(
            graph
                .nodes
                .iter()
                .filter(|node| node.file == "unrelated.py")
                .collect::<Vec<_>>(),
        )
        .unwrap()
    };
    let original_unrelated = unrelated();
    let graph_facts = |db: &std::path::Path| {
        let mut graph = Store::open_read_only(db).unwrap().snapshot().unwrap();
        graph.nodes.sort_by(|a, b| a.id.cmp(&b.id));
        graph.edges.sort_by(|a, b| a.id.cmp(&b.id));
        serde_json::to_value((graph.nodes, graph.edges)).unwrap()
    };
    let mut previous_target = None;
    for (package_source, child_present, target) in [
        ("child = None\n", true, None),
        (
            "from helper import marker as child\n",
            true,
            Some(("helper.py", "function")),
        ),
        ("", true, Some(("pkg/child.py", "module"))),
        ("child = None\n", true, None),
        (
            "from helper import marker as child\n",
            true,
            Some(("helper.py", "function")),
        ),
        ("", false, None),
        ("", true, Some(("pkg/child.py", "module"))),
    ] {
        fs::write(&package, package_source).unwrap();
        if child_present {
            fs::write(&child, "pass\n").unwrap();
        } else {
            fs::remove_file(&child).unwrap();
        }
        assert_eq!(
            index::check_update(dir.path(), &db)
                .unwrap()
                .changed
                .contains(&"consumer.py".into()),
            target != previous_target,
            "consumer invalidation: {package_source:?}, child={child_present}"
        );
        index::run(dir.path(), &db).unwrap();
        index::run_with_options(
            dir.path(),
            &fresh_db,
            &index::IndexOptions {
                force: true,
                ..Default::default()
            },
        )
        .unwrap();
        assert_eq!(
            graph_facts(&db),
            graph_facts(&fresh_db),
            "{package_source:?}, child={child_present}"
        );
        for database in [&db, &fresh_db] {
            let imports = Store::open_read_only(database)
                .unwrap()
                .neighbors(
                    "python:consumer.py:module",
                    &QueryOptions {
                        direction: Direction::Outgoing,
                        relation: Some("imports".into()),
                        ..Default::default()
                    },
                )
                .unwrap();
            assert_eq!(imports.edges.len(), usize::from(target.is_some()));
            assert_eq!(imports.unresolved.len(), usize::from(target.is_none()));
            if let Some((file, kind)) = target {
                let edge = &imports.edges[0];
                assert!(
                    imports.nodes.iter().any(|node| node.id == edge.target
                        && node.file == file
                        && node.kind == kind)
                );
            }
        }
        assert_eq!(unrelated(), original_unrelated);
        assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
        assert!(index::check_update(dir.path(), &db).unwrap().fresh);
        previous_target = target;
    }
}

#[test]
fn configured_source_roots_reject_ambiguous_forwarding_and_restore_after_removal() {
    let dir = tempdir().unwrap();
    fs::create_dir_all(dir.path().join("one/pkg")).unwrap();
    fs::create_dir_all(dir.path().join("two/pkg")).unwrap();
    fs::write(dir.path().join("one/pkg/impl.py"), "def execute(): pass\n").unwrap();
    fs::write(
        dir.path().join("one/pkg/__init__.py"),
        "from .impl import execute as K\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("app.py"),
        "from pkg import K\ndef run(): K()\n",
    )
    .unwrap();
    let options = index::IndexOptions {
        python_source_roots: vec!["one".into(), "two".into()],
        ..Default::default()
    };
    let db = dir.path().join(".graf/index.db");
    let snapshot = || Store::open(&db).unwrap().snapshot().unwrap();
    index::run_with_options(dir.path(), &db, &options).unwrap();
    assert_eq!(
        pairs(&snapshot(), "calls"),
        [("run".into(), "one/pkg/impl.py:execute".into())]
    );
    let collision = dir.path().join("two/pkg/impl.py");
    // Even a different set of definitions cannot disambiguate two module identities.
    fs::write(&collision, "def unrelated(): pass\n").unwrap();
    index::run_with_options(dir.path(), &db, &options).unwrap();
    assert!(pairs(&snapshot(), "calls").is_empty());
    fs::remove_file(collision).unwrap();
    index::run_with_options(dir.path(), &db, &options).unwrap();
    assert_eq!(
        pairs(&snapshot(), "calls"),
        [("run".into(), "one/pkg/impl.py:execute".into())]
    );
}

#[test]
fn resolved_annotations_and_decorators_retain_context_through_public_aliases() {
    let facts = contextualize(inventory(&[
        (
            "pkg/model.py",
            "class Payload: pass\nclass Result: pass\nclass Base: pass\ndef traced(fn): return fn\ndef factory(): pass\n",
        ),
        (
            "pkg/__init__.py",
            "from .model import Payload as Item, Result as Output, Base, traced, factory\n",
        ),
        (
            "service.py",
            "from pkg import Item, Output, Base, traced, factory\n@traced\ndef process(value: Item) -> Output: pass\ndef batch(values: list[Item]) -> Output: pass\nclass Service(Base):\n    field: Item\ndef opaque(value: factory()) -> factory(): pass\n",
        ),
    ]));
    let owner = node(&facts[2], "process").id.clone();
    let dir = tempdir().unwrap();
    let mut store = Store::create(&dir.path().join("index.db")).unwrap();
    store
        .apply_native("fixture-root", facts, vec![], Coverage::default())
        .unwrap();
    let graph = store.snapshot().unwrap();
    for (from, target, relation, context) in [
        ("process", "Payload", "references", "parameter_type"),
        ("process", "Result", "references", "return_type"),
        ("process", "traced", "references", "decorator"),
        ("batch", "Payload", "references", "generic_arg"),
        ("Service", "Payload", "references", "variable_type"),
        ("Service", "Base", "inherits", "base_class"),
    ] {
        assert!(
            graph.edges.iter().any(|e| e.relation == relation
                && e.metadata["context"] == context
                && graph
                    .nodes
                    .iter()
                    .any(|n| n.id == e.source && n.label == from)
                && graph
                    .nodes
                    .iter()
                    .any(|n| n.id == e.target && n.label == target && n.file == "pkg/model.py")),
            "{from} -> {target} ({context})"
        );
    }
    assert!(pairs(&graph, "calls").is_empty());
    let selected = store
        .neighbors_extended(
            &owner,
            &SearchOptions {
                graph: QueryOptions {
                    direction: Direction::Outgoing,
                    relation: Some("references".into()),
                    ..Default::default()
                },
                contexts: vec!["return_type".into()],
                ..Default::default()
            },
        )
        .unwrap();
    assert_eq!(selected.graph.edges.len(), 1);
    assert_eq!(selected.graph.edges[0].metadata["context"], "return_type");
    assert!(selected.graph.nodes.iter().any(|n| n.label == "Result"));
    assert!(!selected.graph.nodes.iter().any(|n| n.label == "Payload"));
}

#[test]
fn terminal_binding_loss_keeps_lookup_keys_for_store_only_rebinding() {
    let consumer = parse_python(
        "consumer.py",
        "from provider import action\ndef caller(): action()\n",
        "consumer",
    )
    .unwrap();
    let valid = parse_python("provider.py", "def action(): pass\n", "valid").unwrap();
    let baseline = PythonContext::from_facts(&[valid.clone(), consumer.clone()]);
    for source in [
        "def action(): pass\naction = replacement\n",
        "def action(arg, arg): pass\n",
        "def action(): pass\nunrelated = replacement\n",
    ] {
        let changed = parse_python("provider.py", source, "changed").unwrap();
        let context = PythonContext::from_facts(&[changed.clone(), consumer.clone()]);
        assert_eq!(baseline.fingerprint(), context.fingerprint(), "{source}");
        let mut caller = consumer.clone();
        context.apply(&mut caller);
        assert_eq!(
            reference(&caller, "caller", "action", "calls").candidate_keys,
            ["python:provider:action"]
        );
        let dir = tempdir().unwrap();
        let mut store = Store::create(&dir.path().join("index.db")).unwrap();
        store
            .apply_native(
                "fixture-root",
                contextualize(vec![valid.clone(), consumer.clone()]),
                vec![],
                Coverage::default(),
            )
            .unwrap();
        let mut changed = changed;
        context.apply(&mut changed);
        // Keep the consumer's stored facts: target-key changes alone rebind it.
        store
            .apply_native("fixture-root", vec![changed], vec![], Coverage::default())
            .unwrap();
        let expected = usize::from(source.contains("unrelated"));
        assert_eq!(
            pairs(&store.snapshot().unwrap(), "calls").len(),
            expected,
            "{source}"
        );
        store
            .apply_native(
                "fixture-root",
                vec![valid.clone()],
                vec![],
                Coverage::default(),
            )
            .unwrap();
        assert_eq!(pairs(&store.snapshot().unwrap(), "calls").len(), 1);
    }
}

#[test]
fn shadowed_member_receivers_refresh_without_binding_a_submodule_collision() {
    let dir = tempdir().unwrap();
    fs::create_dir(dir.path().join("provider")).unwrap();
    let provider = dir.path().join("provider.py");
    let valid = "class Tool:\n    @staticmethod\n    def work(): pass\n";
    fs::write(&provider, valid).unwrap();
    let submodule = dir.path().join("provider/Tool.py");
    fs::write(&submodule, "def unrelated(): pass\n").unwrap();
    fs::write(
        dir.path().join("consumer.py"),
        "from provider import Tool\ndef run(): Tool.work()\n",
    )
    .unwrap();
    let db = dir.path().join(".graf/index.db");
    let calls = || pairs(&Store::open(&db).unwrap().snapshot().unwrap(), "calls");
    index::run(dir.path(), &db).unwrap();
    assert_eq!(calls(), [("run".into(), "provider.py:Tool.work".into())]);
    fs::write(&provider, format!("{valid}Tool = replacement\n")).unwrap();
    fs::write(&submodule, "def work(): pass\n").unwrap();
    index::run(dir.path(), &db).unwrap();
    // The receiver was overwritten: do not use the coincidental submodule alias.
    assert!(calls().is_empty());
    fs::write(&provider, valid).unwrap();
    index::run(dir.path(), &db).unwrap();
    // Both verified aliases exist now, so ambiguity still prevents a call edge.
    assert!(calls().is_empty());
    fs::remove_file(submodule).unwrap();
    index::run(dir.path(), &db).unwrap();
    assert_eq!(calls(), [("run".into(), "provider.py:Tool.work".into())]);
}

#[test]
fn literal_all_and_public_star_chains_preserve_origins_and_import_evidence() {
    let facts = contextualize(inventory(&[
        (
            "pkg/impl.py",
            "def execute(): pass\ndef _hidden(): pass\ndef omitted(): pass\n__all__ = ('execute', '_hidden')\n",
        ),
        ("pkg/api.py", "from .impl import *\n"),
        ("pkg/__init__.py", "from .api import *\n"),
        (
            "app.py",
            "from pkg import *\ndef run():\n    execute()\n    _hidden()\n    omitted()\n",
        ),
        (
            "private.py",
            "from pkg.impl import *\ndef private_run(): _hidden()\n",
        ),
        (
            "explicit.py",
            "from pkg.impl import omitted\ndef explicit_run(): omitted()\n",
        ),
    ]));
    let dir = tempdir().unwrap();
    let mut store = Store::create(&dir.path().join("index.db")).unwrap();
    store
        .apply_native("fixture-root", facts, vec![], Coverage::default())
        .unwrap();
    let graph = store.snapshot().unwrap();
    let mut calls = pairs(&graph, "calls");
    calls.sort();
    // The second star uses api's default public set, so _hidden stops there.
    assert_eq!(
        calls,
        [
            ("explicit_run".into(), "pkg/impl.py:omitted".into()),
            ("private_run".into(), "pkg/impl.py:_hidden".into()),
            ("run".into(), "pkg/impl.py:execute".into()),
        ]
    );
    assert!(pairs(&graph, "imports").contains(&("app".into(), "pkg/impl.py:execute".into())));
    assert!(pairs(&graph, "re_exports").contains(&("pkg".into(), "pkg/api.py:pkg.api".into())));
    assert_eq!(
        graph.nodes.iter().filter(|n| n.label == "execute").count(),
        1
    );
}

#[test]
fn literal_all_can_publish_a_private_named_import_and_public_definitions_need_no_list() {
    let facts = contextualize(inventory(&[
        ("provider.py", "def work(): pass\ndef _private(): pass\n"),
        (
            "api.py",
            "from provider import work as _entry\n__all__ = ['_entry']\n",
        ),
        (
            "app.py",
            "from api import *\nfrom provider import *\ndef run():\n    _entry()\n    work()\n    _private()\n",
        ),
    ]));
    for label in ["_entry", "work"] {
        assert_eq!(
            reference(&facts[2], "run", label, "calls").candidate_keys,
            ["python:provider:work"]
        );
    }
    assert!(
        reference(&facts[2], "run", "_private", "calls")
            .candidate_keys
            .is_empty()
    );
}

#[test]
fn star_enumeration_rejects_dynamic_lists_cycles_missing_modules_and_shadowed_names() {
    for provider in [
        "def work(): pass\n__all__ = build_exports()\n",
        "def work(): pass\n__all__ = ['work']\n__all__.append('other')\n",
        "def work(): pass\nif enabled:\n    __all__ = ['work']\n",
        "def work(): pass\n__all__ = ['wo' + 'rk']\n",
        "def work(): pass\n__all__ = ['\\x77ork']\n",
        "def work(): pass\nwork = replacement\n",
        "def work(): pass\ndel work\n",
        "from consumer import *\ndef work(): pass\n",
        "from missing import *\ndef work(): pass\n",
        "def work(): pass\nglobals()['work'] = replacement\n",
    ] {
        let facts = contextualize(inventory(&[
            ("provider.py", provider),
            ("consumer.py", "from provider import *\ndef run(): work()\n"),
            // An unavailable star name must not fall back to this submodule.
            ("consumer/work.py", "def unrelated(): pass\n"),
        ]));
        assert!(
            reference(&facts[1], "run", "work", "calls")
                .candidate_keys
                .is_empty(),
            "{provider}"
        );
    }
    for consumer in [
        "from provider import *\nwork = replacement\ndef run(): work()\n",
        "from provider import *\ndef run(work): work()\n",
        "from provider import *\nfrom other import *\ndef run(): work()\n",
        "from provider import *\ndef work(): pass\ndef run(): work()\n",
        "if enabled:\n    from provider import *\ndef run(): work()\n",
    ] {
        let facts = contextualize(inventory(&[
            ("provider.py", "def work(): pass\n"),
            ("other.py", "def work(): pass\n"),
            ("consumer.py", consumer),
        ]));
        assert!(
            reference(&facts[2], "run", "work", "calls")
                .candidate_keys
                .is_empty(),
            "{consumer}"
        );
    }
}

#[test]
fn literal_inheritance_uses_c3_overrides_and_forwarded_class_origins() {
    let facts = contextualize(inventory(&[
        (
            "pkg/base.py",
            "class Root(object):\n    @staticmethod\n    def work(): pass\nclass Left(Root): pass\nclass Right(Root):\n    @staticmethod\n    def work(): pass\nclass Diamond(Left, Right): pass\nclass Own(Diamond):\n    @staticmethod\n    def work(): pass\n",
        ),
        (
            "pkg/__init__.py",
            "from .base import Diamond as Public, Own\n",
        ),
        (
            "child.py",
            "from pkg import Public\nclass Leaf(Public): pass\ndef local(): Leaf.work()\n",
        ),
        (
            "app.py",
            "from child import Leaf\nfrom pkg import Own\nimport child as module\ndef run():\n    Leaf.work()\n    Own.work()\n    module.Leaf.work()\n",
        ),
    ]));
    let dir = tempdir().unwrap();
    let mut store = Store::create(&dir.path().join("index.db")).unwrap();
    store
        .apply_native("fixture-root", facts, vec![], Coverage::default())
        .unwrap();
    let graph = store.snapshot().unwrap();
    let calls = pairs(&graph, "calls");
    assert_eq!(calls.len(), 4, "{calls:?}");
    assert_eq!(
        calls
            .iter()
            .filter(|(_, target)| target == "pkg/base.py:Right.work")
            .count(),
        3
    );
    assert!(calls.contains(&("run".into(), "pkg/base.py:Own.work".into())));
    assert!(pairs(&graph, "inherits").contains(&("Leaf".into(), "pkg/base.py:Diamond".into())));
}

#[test]
fn inherited_navigation_rejects_unknown_bases_mro_conflicts_and_member_shadowing() {
    for classes in [
        "class Child(Base):\n    work = replacement\n",
        "class Child(Base):\n    def work(self): pass\n    del work\n",
        "class Child(Base):\n    @replace\n    def work(self): pass\n",
        "class Child(Base, Missing): pass\n",
        "class Child(factory()): pass\n",
        "class Child(Base, metaclass=Meta): pass\n",
        "class Child(Base, **options): pass\n",
        "class Child(Base, Base): pass\n",
        "object = replacement\nclass Child(Base, object): pass\n",
        "from decorators import *\nclass Child(Base):\n    @staticmethod\n    def work(): pass\n",
        "class X: pass\nclass Y: pass\nclass A(X, Y): pass\nclass B(Y, X): pass\nclass Child(A, B, Base): pass\n",
        "class Child(Base): pass\nChild = factory()\n",
        "@replace\nclass Child(Base): pass\n",
    ] {
        let facts = contextualize(inventory(&[
            (
                "base.py",
                "class Base:\n    @staticmethod\n    def work(): pass\n",
            ),
            ("child.py", &format!("from base import Base\n{classes}")),
            (
                "app.py",
                "from child import Child\ndef run(): Child.work()\n",
            ),
            (
                "decorators.py",
                "def staticmethod(fn): return replacement\n",
            ),
        ]));
        assert!(
            reference(&facts[2], "run", "Child.work", "calls")
                .candidate_keys
                .is_empty(),
            "{classes}"
        );
    }
    let facts = contextualize(inventory(&[
        (
            "a.py",
            "from b import B\nclass A(B):\n    def work(self): pass\n",
        ),
        ("b.py", "from a import A\nclass B(A): pass\n"),
        ("app.py", "from b import B\ndef run(): B.work()\n"),
    ]));
    assert!(
        reference(&facts[2], "run", "B.work", "calls")
            .candidate_keys
            .is_empty()
    );
    let facts = contextualize(inventory(&[
        (
            "base.py",
            "class Base:\n    def work(self): pass\nclass Child(Base): pass\n",
        ),
        (
            "app.py",
            "from base import Child\ndef run(value):\n    value.work()\n    Child().work()\n",
        ),
    ]));
    assert!(
        reference(&facts[1], "run", "value.work", "calls")
            .candidate_keys
            .is_empty()
    );
    assert!(
        reference(&facts[1], "run", "<dynamic call>", "calls")
            .candidate_keys
            .is_empty()
    );
}

#[test]
fn inherited_members_reject_submodule_aliases_and_ambiguous_source_roots() {
    let files = inventory(&[
        (
            "base.py",
            "class Base:\n    @staticmethod\n    def work(): pass\n",
        ),
        (
            "child.py",
            "from base import Base\nclass Child(Base): pass\n",
        ),
        ("child/Child.py", "def work(): pass\n"),
        (
            "app.py",
            "from child import Child\ndef run(): Child.work()\n",
        ),
    ]);
    let applied = contextualize(files.clone());
    assert!(
        reference(&applied[3], "run", "Child.work", "calls")
            .candidate_keys
            .is_empty()
    );
    let mut files = files;
    files.remove(2);
    let applied = contextualize(files);
    assert_eq!(
        reference(&applied[2], "run", "Child.work", "calls").candidate_keys,
        ["python-member:base:Base.work"]
    );

    let mut files = vec![
        parse_python_with_source_root(
            "one/provider.py",
            "class Base:\n    def work(self): pass\n",
            "one",
            Some("one"),
        )
        .unwrap(),
        parse_python_with_source_root(
            "two/provider.py",
            "def unrelated(): pass\n",
            "two",
            Some("two"),
        )
        .unwrap(),
        parse_python(
            "child.py",
            "from provider import *\nclass Child(Base): pass\ndef run(): Child.work()\n",
            "child",
        )
        .unwrap(),
    ];
    let applied = contextualize(files.clone());
    assert!(
        reference(&applied[2], "run", "Child.work", "calls")
            .candidate_keys
            .is_empty()
    );
    files.remove(1);
    let applied = contextualize(files);
    assert_eq!(
        reference(&applied[1], "run", "Child.work", "calls").candidate_keys,
        ["python-member:provider:Base.work"]
    );
}

#[test]
fn star_and_inherited_targets_refresh_after_inventory_changes_without_body_churn() {
    let dir = tempdir().unwrap();
    let provider = dir.path().join("provider.py");
    let initial = "class First:\n    @staticmethod\n    def work(): return 1\nclass Second:\n    @staticmethod\n    def work(): return 2\ndef hidden(): pass\n__all__ = ['First']\n";
    fs::write(&provider, initial).unwrap();
    fs::write(dir.path().join("facade.py"), "from provider import *\n").unwrap();
    let child = dir.path().join("child.py");
    fs::write(
        &child,
        "from facade import First\nclass Child(First): pass\n",
    )
    .unwrap();
    fs::write(dir.path().join("app.py"), "from child import Child\nfrom facade import *\ndef run(): Child.work()\ndef star(): First.work()\n").unwrap();
    let db = dir.path().join(".graf/index.db");
    let calls = || pairs(&Store::open(&db).unwrap().snapshot().unwrap(), "calls");
    index::run(dir.path(), &db).unwrap();
    assert_eq!(calls().len(), 2);
    assert!(
        calls()
            .iter()
            .all(|(_, target)| target == "provider.py:First.work")
    );
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    fs::write(&provider, initial.replace("return 1", "return 9")).unwrap();
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 1);
    fs::write(
        &provider,
        initial.replace("['First']", "['First', 'Second']"),
    )
    .unwrap();
    fs::write(
        &child,
        "from facade import Second\nclass Child(Second): pass\n",
    )
    .unwrap();
    index::run(dir.path(), &db).unwrap();
    assert!(calls().contains(&("run".into(), "provider.py:Second.work".into())));
    fs::write(&provider, initial.replace("['First']", "['Second']")).unwrap();
    index::run(dir.path(), &db).unwrap();
    assert_eq!(calls(), [("run".into(), "provider.py:Second.work".into())]);
    fs::write(&provider, initial.replace("['First']", "compute_exports()")).unwrap();
    index::run(dir.path(), &db).unwrap();
    assert!(calls().is_empty());
    fs::write(
        &provider,
        initial.replace("['First']", "['First', 'Second']"),
    )
    .unwrap();
    index::run(dir.path(), &db).unwrap();
    assert_eq!(calls().len(), 2);
    fs::write(
        &child,
        "from facade import Second\nclass Child(Second):\n    work = replacement\n",
    )
    .unwrap();
    index::run(dir.path(), &db).unwrap();
    assert_eq!(calls(), [("star".into(), "provider.py:First.work".into())]);
    fs::remove_file(&provider).unwrap();
    index::run(dir.path(), &db).unwrap();
    assert!(calls().is_empty());
    fs::write(&provider, initial).unwrap();
    index::run(dir.path(), &db).unwrap();
    assert_eq!(calls(), [("star".into(), "provider.py:First.work".into())]);
}

#[test]
fn explicit_imports_retain_local_ownership_until_star_collisions_are_checked() {
    for (path, provider, consumer, colliding, noncolliding, expected) in [
        (
            "first.py",
            "def work(): pass\n",
            "from first import work\nfrom second import *\ndef run(): work()\n",
            "def work(): pass\n",
            "def other(): pass\n",
            "first.py:work",
        ),
        (
            "first.py",
            "class Base:\n    @staticmethod\n    def work(): pass\n",
            "from first import Base\nfrom second import *\ndef run(): Base.work()\n",
            "class Base:\n    @staticmethod\n    def work(): pass\n",
            "class Other:\n    @staticmethod\n    def work(): pass\n",
            "first.py:Base.work",
        ),
        (
            "first.py",
            "class Base:\n    @staticmethod\n    def work(): pass\n",
            "from first import Base\nfrom second import *\nclass Child(Base): pass\ndef run(): Child.work()\n",
            "class Base:\n    @staticmethod\n    def work(): pass\n",
            "class Other:\n    @staticmethod\n    def work(): pass\n",
            "first.py:Base.work",
        ),
        (
            "first.py",
            "def work(): pass\n",
            "import first as backend\nfrom second import *\ndef run(): backend.work()\n",
            "def backend(): pass\n",
            "def other(): pass\n",
            "first.py:work",
        ),
        (
            "first.py",
            "class Base:\n    @staticmethod\n    def work(): pass\n",
            "import first as backend\nfrom second import *\ndef run(): backend.Base.work()\n",
            "def backend(): pass\n",
            "def other(): pass\n",
            "first.py:Base.work",
        ),
        (
            "first.py",
            "def work(): pass\n",
            "from first import work as _entry\nfrom second import *\ndef run(): _entry()\n",
            "def _entry(): pass\n__all__ = ['_entry']\n",
            "def other(): pass\n__all__ = ['other']\n",
            "first.py:work",
        ),
        (
            "pkg/first.py",
            "def work(): pass\n",
            "import pkg.first\nfrom second import *\ndef run(): pkg.first.work()\n",
            "def pkg(): pass\n",
            "def other(): pass\n",
            "pkg/first.py:work",
        ),
    ] {
        // The control changes only the provider's competing export. The second
        // positive removes the star; neither should suppress an explicit import.
        for (second, use_star, resolved) in [
            (colliding, true, false),
            (noncolliding, true, true),
            (colliding, false, true),
        ] {
            let consumer = if use_star {
                consumer.to_owned()
            } else {
                consumer.replace("from second import *\n", "")
            };
            let facts = contextualize(inventory(&[
                (path, provider),
                ("second.py", second),
                ("consumer.py", &consumer),
            ]));
            let run = node(&facts[2], "run").id.clone();
            let dir = tempdir().unwrap();
            let mut store = Store::create(&dir.path().join("index.db")).unwrap();
            store
                .apply_native("fixture-root", facts, vec![], Coverage::default())
                .unwrap();
            let graph = store.snapshot().unwrap();
            let calls = pairs(&graph, "calls");
            if resolved {
                assert_eq!(
                    calls,
                    [("run".into(), expected.into())],
                    "{consumer}\n{second}"
                );
            } else {
                assert!(calls.is_empty(), "{consumer}\n{second}: {calls:?}");
                assert!(
                    store
                        .neighbors(
                            &run,
                            &QueryOptions {
                                direction: Direction::Outgoing,
                                relation: Some("calls".into()),
                                ..Default::default()
                            }
                        )
                        .unwrap()
                        .unresolved
                        .iter()
                        .any(|r| r.source == run && r.relation == "calls")
                );
            }
            if consumer.contains("class Child") {
                assert_eq!(pairs(&graph, "inherits").len(), usize::from(resolved));
            }
        }
    }
    // A function-local import wins in its own lexical scope; module stars do
    // not overwrite it. A blanket module-level suppression would fail here.
    let facts = contextualize(inventory(&[
        ("first.py", "def work(): pass\n"),
        ("second.py", "def work(): pass\n"),
        (
            "consumer.py",
            "from second import *\ndef run():\n    from first import work\n    work()\n",
        ),
    ]));
    let dir = tempdir().unwrap();
    let mut store = Store::create(&dir.path().join("index.db")).unwrap();
    store
        .apply_native("fixture-root", facts, vec![], Coverage::default())
        .unwrap();
    assert_eq!(
        pairs(&store.snapshot().unwrap(), "calls"),
        [("run".into(), "first.py:work".into())]
    );
}

#[test]
fn explicit_import_star_collision_updates_clear_and_restore_calls_and_bases() {
    let dir = tempdir().unwrap();
    fs::write(
        dir.path().join("first.py"),
        "def work(): pass\nclass Base:\n    @staticmethod\n    def work(): pass\n",
    )
    .unwrap();
    let second = dir.path().join("second.py");
    fs::write(&second, "def other(): pass\n").unwrap();
    fs::write(dir.path().join("consumer.py"), "from first import work, Base\nimport first as backend\nfrom second import *\nclass Child(Base): pass\ndef direct(): work()\ndef member(): Base.work()\ndef module(): backend.work()\ndef inherited(): Child.work()\n").unwrap();
    let db = dir.path().join(".graf/index.db");
    let snapshot = || Store::open(&db).unwrap().snapshot().unwrap();
    index::run(dir.path(), &db).unwrap();
    let mut expected: Vec<(String, String)> = vec![
        ("direct".into(), "first.py:work".into()),
        ("member".into(), "first.py:Base.work".into()),
        ("module".into(), "first.py:work".into()),
        ("inherited".into(), "first.py:Base.work".into()),
    ];
    expected.sort();
    let mut initial = pairs(&snapshot(), "calls");
    initial.sort();
    assert_eq!(initial, expected);
    fs::write(
        &second,
        "def work(): pass\nclass Base: pass\ndef backend(): pass\n",
    )
    .unwrap();
    index::run(dir.path(), &db).unwrap();
    assert!(pairs(&snapshot(), "calls").is_empty());
    assert!(pairs(&snapshot(), "inherits").is_empty());
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    fs::write(&second, "def other(): pass\n").unwrap();
    index::run(dir.path(), &db).unwrap();
    let mut restored = pairs(&snapshot(), "calls");
    restored.sort();
    assert_eq!(restored, expected);
    assert_eq!(
        pairs(&snapshot(), "inherits"),
        [("Child".into(), "first.py:Base".into())]
    );
}

#[test]
fn adding_and_removing_inherited_calls_only_refreshes_the_edited_file() {
    let dir = tempdir().unwrap();
    let model = dir.path().join("model.py");
    let declarations =
        "class Base:\n    @staticmethod\n    def work(): return 1\nclass Child(Base): pass\n";
    let initial = format!("{declarations}def run(): pass\n");
    fs::write(&model, &initial).unwrap();
    fs::write(dir.path().join("unrelated.py"), "def keep(): pass\n").unwrap();
    let db = dir.path().join(".graf/index.db");
    index::run(dir.path(), &db).unwrap();
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    let baseline = PythonContext::from_facts(&inventory(&[
        ("model.py", &initial),
        ("unrelated.py", "def keep(): pass\n"),
    ]));
    for body in [
        "Child.work()",
        "pass",
        "return 7",
        "Base.work()",
        "pass",
        "Child.work()",
        "pass",
    ] {
        let source = format!("{declarations}def run(): {body}\n");
        let context = PythonContext::from_facts(&inventory(&[
            ("model.py", &source),
            ("unrelated.py", "def keep(): pass\n"),
        ]));
        assert_eq!(baseline.fingerprint(), context.fingerprint(), "{body}");
        fs::write(&model, source).unwrap();
        let updated = index::run(dir.path(), &db).unwrap();
        assert_eq!(updated.parsed_files, 1, "{body}");
        assert_eq!(updated.unchanged_files, 1, "{body}");
        let calls = pairs(&Store::open(&db).unwrap().snapshot().unwrap(), "calls");
        if body.ends_with("work()") {
            assert_eq!(calls, [("run".into(), "model.py:Base.work".into())]);
        } else {
            assert!(calls.is_empty(), "{body}: {calls:?}");
        }
        assert_eq!(
            index::run(dir.path(), &db).unwrap().parsed_files,
            0,
            "{body}"
        );
    }
}

#[test]
fn inherited_binding_changes_refresh_existing_consumers_without_reference_changes() {
    let dir = tempdir().unwrap();
    let model = dir.path().join("model.py");
    let declarations = "class First:\n    @staticmethod\n    def work(): pass\nclass Second:\n    @staticmethod\n    def work(): pass\n";
    fs::write(
        dir.path().join("consumer.py"),
        "from model import Child\ndef run(): Child.work()\n",
    )
    .unwrap();
    let db = dir.path().join(".graf/index.db");
    let mut previous = None;
    for (child, expected) in [
        ("class Child(First): pass\n", Some("model.py:First.work")),
        ("class Child(Second): pass\n", Some("model.py:Second.work")),
        (
            "class Child(Second):\n    @staticmethod\n    def work(): pass\n",
            Some("model.py:Child.work"),
        ),
        ("class Child(Second):\n    work = replacement\n", None),
        ("class Child(Second): pass\n", Some("model.py:Second.work")),
        ("class Child(Missing): pass\n", None),
        (
            "class Child:\n    @staticmethod\n    def work(): pass\n",
            Some("model.py:Child.work"),
        ),
        (
            "class Child:\n    @staticmethod\n    def work(): pass\nChild = replacement\n",
            None,
        ),
        ("class Child(First): pass\n", Some("model.py:First.work")),
    ] {
        let source = format!("{declarations}{child}");
        // Consumer references are absent here on purpose: inventory semantics,
        // including suppressed targets, must change the shared context by itself.
        let context = PythonContext::from_facts(&inventory(&[("model.py", &source)]));
        if let Some(previous) = previous {
            assert_ne!(previous, context.fingerprint(), "{child}");
        }
        previous = Some(context.fingerprint().to_owned());
        fs::write(&model, source).unwrap();
        index::run(dir.path(), &db).unwrap();
        let calls = pairs(&Store::open(&db).unwrap().snapshot().unwrap(), "calls");
        match expected {
            Some(target) => assert_eq!(calls, [("run".into(), target.into())], "{child}"),
            None => assert!(calls.is_empty(), "{child}: {calls:?}"),
        }
        assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    }
}

#[test]
fn ordinary_terminal_member_addition_and_deletion_use_store_rebinding() {
    let dir = tempdir().unwrap();
    let provider = dir.path().join("provider.py");
    let present = "class Tool:\n    @staticmethod\n    def work(): pass\n";
    let absent = "class Tool: pass\n";
    fs::write(&provider, absent).unwrap();
    fs::write(
        dir.path().join("consumer.py"),
        "from provider import Tool\ndef run(): Tool.work()\n",
    )
    .unwrap();
    fs::write(dir.path().join("unrelated.py"), "def keep(): pass\n").unwrap();
    let db = dir.path().join(".graf/index.db");
    index::run(dir.path(), &db).unwrap();
    let baseline = PythonContext::from_facts(&inventory(&[("provider.py", present)]));
    assert!(pairs(&Store::open(&db).unwrap().snapshot().unwrap(), "calls").is_empty());
    for (source, count) in [
        (present, 1),
        (absent, 0),
        (present, 1),
        ("", 0),
        (present, 1),
        ("Tool = replacement\n", 0),
        (present, 1),
        (absent, 0),
    ] {
        let context = PythonContext::from_facts(&inventory(&[("provider.py", source)]));
        assert_eq!(baseline.fingerprint(), context.fingerprint());
        fs::write(&provider, source).unwrap();
        let updated = index::run(dir.path(), &db).unwrap();
        assert_eq!(updated.parsed_files, 1);
        assert_eq!(updated.unchanged_files, 2);
        let calls = pairs(&Store::open(&db).unwrap().snapshot().unwrap(), "calls");
        assert_eq!(calls.len(), count);
        if count == 1 {
            assert_eq!(calls, [("run".into(), "provider.py:Tool.work".into())]);
        }
        assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    }
}

#[test]
fn module_member_candidates_require_verified_classes_not_runtime_receivers() {
    let consumer = "import pkg.helpers as h\ndef run(): h.object.method()\n";
    let raw = parse_python("src/pkg/code.py", consumer, "consumer").unwrap();
    assert_eq!(
        reference(&raw, "run", "h.object.method", "calls").candidate_keys,
        ["python-member:pkg.helpers:object.method"]
    );
    for (provider, submodule, expected) in [
        (
            "class object:\n    @staticmethod\n    def method(): pass\n",
            false,
            Some("src/pkg/helpers.py:object.method"),
        ),
        (
            "class Base:\n    @staticmethod\n    def method(): pass\nclass object(Base): pass\n",
            false,
            Some("src/pkg/helpers.py:Base.method"),
        ),
        (
            "class Impl:\n    def method(self): pass\nobject = Impl()\n",
            false,
            None,
        ),
        (
            "class Impl:\n    def method(self): pass\nobject = Impl()\n",
            true,
            None,
        ),
        ("def object():\n    def method(): pass\n", false, None),
        (
            "class object:\n    @staticmethod\n    def method(): pass\nobject = replacement\n",
            false,
            None,
        ),
        (
            "from missing import *\nclass object:\n    def method(self): pass\n",
            false,
            None,
        ),
    ] {
        let mut facts = inventory(&[
            ("src/pkg/code.py", consumer),
            ("src/pkg/helpers.py", provider),
        ]);
        if submodule {
            facts.extend(inventory(&[(
                "src/pkg/helpers/object.py",
                "def method(): pass\n",
            )]));
        }
        let facts = contextualize(facts);
        let owner = node(&facts[0], "run").id.clone();
        let dir = tempdir().unwrap();
        let mut store = Store::create(&dir.path().join("index.db")).unwrap();
        store
            .apply_native("fixture-root", facts, vec![], Coverage::default())
            .unwrap();
        let graph = store.snapshot().unwrap();
        let calls: Vec<_> = pairs(&graph, "calls")
            .into_iter()
            .filter(|(source, _)| source == "run")
            .collect();
        match expected {
            Some(target) => assert_eq!(calls, [("run".into(), target.into())], "{provider}"),
            None => {
                assert!(calls.is_empty(), "{provider}: {calls:?}");
                let result = store
                    .neighbors(
                        &owner,
                        &QueryOptions {
                            direction: Direction::Outgoing,
                            relation: Some("calls".into()),
                            ..Default::default()
                        },
                    )
                    .unwrap();
                assert_eq!(result.unresolved.len(), 1, "{provider}");
            }
        }
    }
}

#[test]
fn star_dependent_definition_keys_and_aliases_wait_for_context_validation() {
    let source = "def target():\n    pass\nfrom other import *\n";
    let consumer = "from pkg.code import target\nimport pkg as p\ndef direct(): target()\ndef alias(): p.code.target()\n";
    for (other, publish) in [
        (None, false),
        (Some("def other(): pass\n"), true),
        (Some("def target(): pass\n"), false),
        (
            Some("def other(): pass\n__all__ = compute_exports()\n"),
            false,
        ),
        (Some("def target(): pass\n__all__ = []\n"), true),
        (Some("__all__ = ['target']\n"), false),
    ] {
        let mut facts = inventory(&[("src/pkg/code.py", source), ("consumer.py", consumer)]);
        if let Some(other) = other {
            facts.extend(inventory(&[("other.py", other)]));
        }
        let target = node(&facts[0], "target");
        assert!(target.binding_key.is_none());
        assert!(target.metadata.get("binding_aliases").is_none());
        // Store must not accidentally publish a raw provisional key/alias. Both
        // consumer candidates would otherwise bind without any context check.
        let dir = tempdir().unwrap();
        let mut store = Store::create(&dir.path().join("index.db")).unwrap();
        store
            .apply_native("fixture-root", facts.clone(), vec![], Coverage::default())
            .unwrap();
        assert!(pairs(&store.snapshot().unwrap(), "calls").is_empty());
        let facts = contextualize(facts);
        let target = node(&facts[0], "target");
        assert_eq!(
            target.binding_key.as_deref(),
            publish.then_some("python:pkg.code:target"),
            "{other:?}"
        );
        assert_eq!(
            target.metadata.get("binding_aliases").is_some(),
            publish,
            "{other:?}"
        );
        store
            .apply_native("fixture-root", facts, vec![], Coverage::default())
            .unwrap();
        let mut calls = pairs(&store.snapshot().unwrap(), "calls");
        calls.sort();
        if publish {
            assert_eq!(
                calls,
                [
                    ("alias".into(), "src/pkg/code.py:target".into()),
                    ("direct".into(), "src/pkg/code.py:target".into()),
                ],
                "{other:?}"
            );
        } else {
            assert!(calls.is_empty(), "{other:?}: {calls:?}");
        }
    }
}

#[test]
fn star_provider_updates_publish_and_retract_definitions_and_member_aliases() {
    let dir = tempdir().unwrap();
    fs::create_dir(dir.path().join("pkg")).unwrap();
    fs::write(
        dir.path().join("pkg/code.py"),
        "def target(): pass\nfrom other import *\n",
    )
    .unwrap();
    fs::write(dir.path().join("consumer.py"), "from pkg.code import target\nimport pkg as p\ndef direct(): target()\ndef alias(): p.code.target()\n").unwrap();
    let other = dir.path().join("other.py");
    let db = dir.path().join(".graf/index.db");
    for (source, publish) in [
        (None, false),
        (Some("def other(): pass\n"), true),
        (Some("def target(): pass\n"), false),
        (Some("def other(): pass\n"), true),
        (Some("__all__ = exports()\n"), false),
        (Some("def other(): pass\n"), true),
        (None, false),
    ] {
        match source {
            Some(source) => fs::write(&other, source).unwrap(),
            None if other.exists() => fs::remove_file(&other).unwrap(),
            None => {}
        }
        index::run(dir.path(), &db).unwrap();
        let graph = Store::open(&db).unwrap().snapshot().unwrap();
        let target = graph
            .nodes
            .iter()
            .find(|n| n.file == "pkg/code.py" && n.label == "target")
            .unwrap();
        assert_eq!(
            target.binding_key.as_deref(),
            publish.then_some("python:pkg.code:target"),
            "{source:?}"
        );
        assert_eq!(
            target.metadata["binding_aliases"]
                .as_array()
                .is_some_and(|aliases| {
                    aliases
                        .iter()
                        .any(|alias| alias.as_str().is_some_and(|key| key.starts_with("python")))
                }),
            publish,
            "{source:?}"
        );
        let mut calls = pairs(&graph, "calls");
        calls.sort();
        if publish {
            assert_eq!(
                calls,
                [
                    ("alias".into(), "pkg/code.py:target".into()),
                    ("direct".into(), "pkg/code.py:target".into()),
                ]
            );
        } else {
            assert!(calls.is_empty(), "{source:?}: {calls:?}");
        }
        assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    }
}

fn receiver_call_pairs(graph: &GraphSnapshot) -> Vec<(String, String)> {
    let mut pairs: Vec<_> = graph
        .edges
        .iter()
        .filter(|e| e.relation == "calls")
        .map(|e| {
            let source = graph.nodes.iter().find(|n| n.id == e.source).unwrap();
            let target = graph.nodes.iter().find(|n| n.id == e.target).unwrap();
            (
                format!(
                    "{}:{}",
                    source.file,
                    source.qualified_name.as_deref().unwrap()
                ),
                format!(
                    "{}:{}",
                    target.file,
                    target.qualified_name.as_deref().unwrap()
                ),
            )
        })
        .collect();
    pairs.sort();
    pairs
}

// The same independent expected endpoints must survive both public ingestion
// paths. No candidate key or resolver result supplies the expected answer.
fn check_receiver_navigation(files: &[(&str, &str)], expected: &[(&str, &str)]) {
    let mut expected: Vec<_> = expected
        .iter()
        .map(|(a, b)| (a.to_string(), b.to_string()))
        .collect();
    expected.sort();
    let dir = tempdir().unwrap();
    let mut store = Store::create(&dir.path().join("direct.db")).unwrap();
    store
        .apply_native(
            "fixture-root",
            contextualize(inventory(files)),
            vec![],
            Coverage::default(),
        )
        .unwrap();
    assert_eq!(
        receiver_call_pairs(&store.snapshot().unwrap()),
        expected,
        "Store: {files:?}"
    );
    let root = dir.path().join("project");
    fs::create_dir(&root).unwrap();
    for (path, source) in files {
        let path = root.join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, source).unwrap();
    }
    let db = root.join(".graf/index.db");
    index::run(&root, &db).unwrap();
    let graph = Store::open(&db).unwrap().snapshot().unwrap();
    assert_eq!(receiver_call_pairs(&graph), expected, "index: {files:?}");
    for edge in graph.edges.iter().filter(|e| e.relation == "calls") {
        assert_eq!(edge.metadata["context"], "receiver_declaration");
    }
    assert_eq!(index::run(&root, &db).unwrap().parsed_files, 0);
}

#[test]
fn implicit_receivers_keep_class_identity_across_files_and_builtin_descriptors() {
    check_receiver_navigation(
        &[
            (
                "pkg/base.py",
                "class Parent:\n    def inherited(self): return 1\n    @classmethod\n    def construct(cls): return 2\n",
            ),
            ("pkg/__init__.py", "from .base import Parent as Public\n"),
            (
                "worker.py",
                r#"from pkg import Public
class Worker(Public):
    def local(self): return 3
    @staticmethod
    def utility(): return 4
    @classmethod
    def class_local(cls): return 5
    def via_self(self): return self.local()
    def via_inherited(this): return this.inherited()
    def via_static(self): return self.utility()
    def via_typed(this: 'Worker'): return this.local()
    @classmethod
    def via_cls(cls): return cls.construct()
    @classmethod
    def via_cls_local(cls): return cls.class_local()
    def via_super(self): return super().inherited()
    @classmethod
    def via_class_super(cls): return super().construct()
    def initialized(self):
        self.state = 1
        return self.local()
class Decoy:
    def local(self): return 99
    def inherited(self): return 99
def local(): return 99
def opaque(factory): return factory().local()
"#,
            ),
        ],
        &[
            ("worker.py:Worker.via_self", "worker.py:Worker.local"),
            (
                "worker.py:Worker.via_inherited",
                "pkg/base.py:Parent.inherited",
            ),
            ("worker.py:Worker.via_static", "worker.py:Worker.utility"),
            ("worker.py:Worker.via_typed", "worker.py:Worker.local"),
            ("worker.py:Worker.via_cls", "pkg/base.py:Parent.construct"),
            (
                "worker.py:Worker.via_cls_local",
                "worker.py:Worker.class_local",
            ),
            ("worker.py:Worker.via_super", "pkg/base.py:Parent.inherited"),
            (
                "worker.py:Worker.via_class_super",
                "pkg/base.py:Parent.construct",
            ),
            ("worker.py:Worker.initialized", "worker.py:Worker.local"),
        ],
    );
}

#[test]
fn implicit_receivers_reject_shadowing_mutation_overloads_and_dynamic_descriptors() {
    let base = "class Base:\n    def work(self): return 1\n";
    let supported =
        "from base import Base\nclass Child(Base):\n    def run(self): return self.work()\n";
    check_receiver_navigation(
        &[("base.py", base), ("child.py", supported)],
        &[("child.py:Child.run", "base.py:Base.work")],
    );
    for source in [
        "class Child(Base):\n    def run(self):\n        self = other\n        return self.work()\n",
        "class Child(Base):\n    def run(self):\n        self.work()\n        self = other\n",
        "class Child(Base):\n    def run(self):\n        self.work = other\n        return self.work()\n",
        "class Child(Base):\n    def __init__(self): self.work = other\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def mutate(self): del self.work\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def mutate(self): delattr(self, 'work')\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def mutate(self): setattr(self, 'work', other)\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def mutate(self, name): setattr(self, name, other)\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def mutate(self): self.__dict__['work'] = other\n    def run(self): return self.work()\n",
        "class Child(Base):\n    work = other\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def work(self): return 2\n    def work(self): return 3\n    def run(self): return self.work()\n",
        "class Child(Base):\n    @overload\n    def work(self): ...\n    def work(self): return 3\n    def run(self): return self.work()\n",
        "class Child(Base):\n    @property\n    def work(self): return other\n    def run(self): return self.work()\n",
        "class Child(Base):\n    @unknown\n    def work(self): return 2\n    def run(self): return self.work()\n",
        "class Child(Base):\n    @staticmethod\n    def run(self): return self.work()\n",
        "classmethod = unknown\nclass Child(Base):\n    @classmethod\n    def run(cls): return cls.work()\n",
        "class Child(Base):\n    def run(self, other): return other.work()\n",
        "class Child(Base):\n    def run(self): return self.child.work()\n",
        "class Child(Base):\n    def run(self):\n        def inner(self): return self.work()\n",
        "class Child(Base):\n    def run(self):\n        def inner(): return super().work()\n",
        "class Child(Base):\n    def run(self, super): return super().work()\n",
        "super = replacement\nclass Child(Base):\n    def run(self): return super().work()\n",
        "class Child(Base):\n    def run(self):\n        self.__class__ = other\n        return super().work()\n",
        "class Child(Base):\n    def run(self): return super(Child, self).work()\n",
        "class Child(Base):\n    def __getattribute__(self, name): return other\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def __getattr__(self, name): return other\n    def run(self): return self.work()\n",
        "class Child(Base):\n    def run(self): return self.work()\nChild = other\n",
        "class Child(Base, metaclass=custom):\n    def run(self): return self.work()\n",
    ] {
        let source = format!("from base import Base\n{source}");
        check_receiver_navigation(&[("base.py", base), ("child.py", &source)], &[]);
    }
}

#[test]
fn implicit_receivers_use_c3_and_preserve_visible_override_uncertainty() {
    let base = "class Root:\n    def work(self): return 1\nclass Left(Root): pass\nclass Right(Root):\n    def work(self): return 2\n";
    check_receiver_navigation(
        &[(
            "model.py",
            &format!(
                "{base}class Child(Left, Right):\n    def run(self): return self.work()\n    def via_super(self): return super().work()\n"
            ),
        )],
        &[
            ("model.py:Child.run", "model.py:Right.work"),
            ("model.py:Child.via_super", "model.py:Right.work"),
        ],
    );
    for tail in [
        "class Conflict(Left, Right): pass\nclass Reverse(Right, Left): pass\nclass Child(Conflict, Reverse):\n    def run(self): return self.work()\n",
        "class Child(Unknown, Root):\n    def run(self): return self.work()\n",
        "class Child(Root):\n    def run(self): return self.work()\nclass Override(Child):\n    def work(self): return 3\n",
        "class Child(Root):\n    def run(self): return self.work()\nclass UnknownChild(Child, Unknown): pass\n",
        "class Child(Left):\n    def run(self): return super().work()\nclass Reordered(Child, Right): pass\n",
    ] {
        check_receiver_navigation(&[("model.py", &format!("{base}{tail}"))], &[]);
    }
}

#[test]
fn implicit_receiver_member_evidence_cannot_borrow_a_submodule_alias() {
    check_receiver_navigation(
        &[
            (
                "pkg/model.py",
                "class Child:\n    class work: pass\n    def run(self): return self.work()\n",
            ),
            ("pkg/model/Child.py", "def work(): return 9\n"),
        ],
        &[],
    );
}

#[test]
fn implicit_receiver_missing_member_rejects_submodule_alias() {
    let missing = "class Child:\n    def run(self): return self.work()\n";
    let actual =
        "class Child:\n    def run(self): return self.work()\n    def work(self): return 1\n";
    for files in [
        vec![("pkg/model.py", missing)],
        vec![
            ("pkg/model.py", missing),
            ("pkg/model/Child.py", "def work(): return 9\n"),
        ],
    ] {
        let facts = contextualize(inventory(&files));
        let keys = &reference(&facts[0], "Child.run", "self.work", "calls").candidate_keys;
        if files.len() == 1 {
            // Keep the safe unresolved terminal key for later Store rebinding.
            assert_eq!(keys, &["python-member:pkg.model:Child.work"]);
        } else {
            assert!(keys.is_empty());
        }
        check_receiver_navigation(&files, &[]);
    }
    check_receiver_navigation(
        &[("pkg/model.py", actual)],
        &[("pkg/model.py:Child.run", "pkg/model.py:Child.work")],
    );
    assert_eq!(
        PythonContext::from_facts(&inventory(&[("pkg/model.py", missing)])).fingerprint(),
        PythonContext::from_facts(&inventory(&[("pkg/model.py", actual)])).fingerprint(),
        "ordinary terminal method addition must not invalidate unrelated files",
    );
}

#[test]
fn receiver_missing_member_collision_refreshes_only_on_binding_changes() {
    let dir = tempdir().unwrap();
    let model = dir.path().join("pkg/model.py");
    let decoy = dir.path().join("pkg/model/Child.py");
    fs::create_dir_all(decoy.parent().unwrap()).unwrap();
    let missing = "class Child:\n    def run(self): return self.work()\n";
    let actual =
        "class Child:\n    def run(self): return self.work()\n    def work(self): return 1\n";
    let unrelated = "def keep(): return 1\n";
    fs::write(&model, missing).unwrap();
    fs::write(dir.path().join("unrelated.py"), unrelated).unwrap();
    let db = dir.path().join(".graf/index.db");
    index::run(dir.path(), &db).unwrap();
    let unrelated_nodes = || {
        let graph = Store::open_read_only(&db).unwrap().snapshot().unwrap();
        serde_json::to_value(
            graph
                .nodes
                .iter()
                .filter(|node| node.file == "unrelated.py")
                .collect::<Vec<_>>(),
        )
        .unwrap()
    };
    let original_unrelated = unrelated_nodes();
    assert!(receiver_call_pairs(&Store::open(&db).unwrap().snapshot().unwrap()).is_empty());
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    let baseline = PythonContext::from_facts(&inventory(&[
        ("pkg/model.py", missing),
        ("unrelated.py", unrelated),
    ]));
    let mut collision_fingerprint = None;
    for (source, parsed, unchanged) in [
        ("def work(): return 9\n", 2, 1),
        ("def work(): return 10\n", 1, 2),
    ] {
        fs::write(&decoy, source).unwrap();
        let context = PythonContext::from_facts(&inventory(&[
            ("pkg/model.py", missing),
            ("pkg/model/Child.py", source),
            ("unrelated.py", unrelated),
        ]));
        assert_ne!(baseline.fingerprint(), context.fingerprint());
        if let Some(previous) = &collision_fingerprint {
            assert_eq!(
                previous,
                context.fingerprint(),
                "decoy body edits keep the same proof"
            );
        }
        collision_fingerprint = Some(context.fingerprint().to_owned());
        let update = index::run(dir.path(), &db).unwrap();
        assert_eq!(update.parsed_files, parsed);
        assert_eq!(update.unchanged_files, unchanged);
        assert_eq!(unrelated_nodes(), original_unrelated);
        assert!(receiver_call_pairs(&Store::open(&db).unwrap().snapshot().unwrap()).is_empty());
        assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    }
    fs::remove_file(&decoy).unwrap();
    let update = index::run(dir.path(), &db).unwrap();
    assert_eq!(
        update.parsed_files, 1,
        "removing the collision restores the terminal lookup"
    );
    assert_eq!(update.unchanged_files, 1);
    assert_eq!(unrelated_nodes(), original_unrelated);
    assert!(receiver_call_pairs(&Store::open(&db).unwrap().snapshot().unwrap()).is_empty());
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    fs::write(&model, actual).unwrap();
    let context = PythonContext::from_facts(&inventory(&[
        ("pkg/model.py", actual),
        ("unrelated.py", unrelated),
    ]));
    assert_eq!(baseline.fingerprint(), context.fingerprint());
    let update = index::run(dir.path(), &db).unwrap();
    assert_eq!(update.parsed_files, 1);
    assert_eq!(update.unchanged_files, 1);
    assert_eq!(
        receiver_call_pairs(&Store::open(&db).unwrap().snapshot().unwrap()),
        [(
            "pkg/model.py:Child.run".into(),
            "pkg/model.py:Child.work".into()
        )],
    );
    assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
}

#[test]
fn receiver_body_edits_do_not_broaden_incremental_invalidation() {
    let dir = tempdir().unwrap();
    let base = "class Parent:\n    def work(self): return 1\n";
    fs::write(dir.path().join("base.py"), base).unwrap();
    fs::write(dir.path().join("unrelated.py"), "def keep(): return 1\n").unwrap();
    let db = dir.path().join(".graf/index.db");
    let mut fingerprint = None;
    for body in [
        "pass",
        "self.work()",
        "super().work()",
        "return 42",
        "self.state = 7",
        "self.work()",
        "pass",
    ] {
        let caller =
            format!("from base import Parent\nclass Child(Parent):\n    def run(self): {body}\n");
        let context =
            PythonContext::from_facts(&inventory(&[("base.py", base), ("caller.py", &caller)]));
        fs::write(dir.path().join("caller.py"), &caller).unwrap();
        let update = index::run(dir.path(), &db).unwrap();
        if let Some(previous) = &fingerprint {
            assert_eq!(previous, context.fingerprint(), "{body}");
            assert_eq!(update.parsed_files, 1, "{body}");
            assert_eq!(update.unchanged_files, 2, "{body}");
        }
        fingerprint = Some(context.fingerprint().to_owned());
        let expected = if body.ends_with("work()") {
            vec![("caller.py:Child.run".into(), "base.py:Parent.work".into())]
        } else {
            vec![]
        };
        assert_eq!(
            receiver_call_pairs(&Store::open(&db).unwrap().snapshot().unwrap()),
            expected,
            "{body}"
        );
        assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    }
}

#[test]
fn receiver_navigation_refreshes_after_replacement_deletion_and_override_changes() {
    let dir = tempdir().unwrap();
    let caller = "from base import Parent\nclass Child(Parent):\n    def run(self): return self.work()\n    def parent(self): return super().work()\n";
    fs::write(dir.path().join("caller.py"), caller).unwrap();
    let db = dir.path().join(".graf/index.db");
    let mut direct = Store::create(&dir.path().join("direct.db")).unwrap();
    for (base, subclass, target) in [
        (
            Some("class Parent:\n    def work(self): return 1\n"),
            "",
            Some("Parent.work"),
        ),
        (
            Some("class Root:\n    def work(self): return 2\nclass Parent(Root): pass\n"),
            "",
            Some("Root.work"),
        ),
        (Some("class Parent:\n    work = replacement\n"), "", None),
        (
            Some("class Parent:\n    def work(self): return 3\n"),
            "",
            Some("Parent.work"),
        ),
        (None, "", None),
        (
            Some("class Parent:\n    def work(self): return 4\n"),
            "",
            Some("Parent.work"),
        ),
        (Some("def Parent(): pass\n"), "", None),
        (
            Some("class Parent:\n    def work(self): return 5\n"),
            "from caller import Child\nclass Override(Child):\n    def work(self): return 6\n",
            Some("Parent.work"),
        ),
        (
            Some("class Parent:\n    def work(self): return 5\n"),
            "",
            Some("Parent.work"),
        ),
    ] {
        let mut files = vec![("caller.py", caller), ("subclass.py", subclass)];
        let deleted = if let Some(base) = base {
            files.push(("base.py", base));
            fs::write(dir.path().join("base.py"), base).unwrap();
            vec![]
        } else {
            fs::remove_file(dir.path().join("base.py")).unwrap();
            vec!["base.py".into()]
        };
        fs::write(dir.path().join("subclass.py"), subclass).unwrap();
        direct
            .apply_native(
                "fixture-root",
                contextualize(inventory(&files)),
                deleted,
                Coverage::default(),
            )
            .unwrap();
        index::run(dir.path(), &db).unwrap();
        let mut expected = Vec::new();
        if let Some(target) = target {
            expected.push(("caller.py:Child.parent".into(), format!("base.py:{target}")));
            if subclass.is_empty() {
                expected.push(("caller.py:Child.run".into(), format!("base.py:{target}")));
            }
        }
        expected.sort();
        assert_eq!(
            receiver_call_pairs(&direct.snapshot().unwrap()),
            expected,
            "Store: {files:?}"
        );
        assert_eq!(
            receiver_call_pairs(&Store::open(&db).unwrap().snapshot().unwrap()),
            expected,
            "index: {files:?}"
        );
        assert_eq!(index::run(dir.path(), &db).unwrap().parsed_files, 0);
    }
}
